var date=new Date();
document.write(date+"<br>");
var year=date.getFullYear();
document.write(year+"<br>");
var month=date.getMonth();
document.write(month+"<br>");
var currentdate=date.getDate();
document.write(currentdate+"<br>");
var currentday=date.getDay();
document.write(currentday+"<br>");
var curminuets=date.getMinutes();
document.write(curminuets);
